# config/services_test.yaml
services:
    App\Security\JwtEnableVoter:
        arguments:
            $jwtEnabled: 'true'
    App\Security\TestAuthenticator:
        arguments:
            $security: '@security.helper'